# Generated by Django 4.0.2 on 2022-03-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titles',
            new_name='title',
        ),
    ]
