# Generated by Django 4.0.4 on 2022-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_titles_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
