# Generated by Django 4.0.4 on 2022-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
