# Generated by Django 4.0.4 on 2022-04-11 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_alter_todo_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
